version: '3.11'
services:
  app:
    build: .
    volumes:
     - .:/django
    ports:
     - 8000:8000
    image: projectx:django
    container_name: app_container
    command: gunicorn ProjectX.wsgi:application --bind 0.0.0.0:8000